[2018-05-29 18:21:17,808] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 18:21:18,359] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run example query.q6 2018-05-29T18:21:16.048103 --job_id 9 --raw -sd DAGS_FOLDER/example.py']
[2018-05-29 18:21:18,556] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:18,556] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 18:21:18,787] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:18,787] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 18:21:19,177] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,177] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 18:21:16.048103 [queued]>
[2018-05-29 18:21:19,178] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,178] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 18:21:16.048103 [queued]>
[2018-05-29 18:21:19,178] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,178] {models.py:1318} INFO - 
[2018-05-29 18:21:19,178] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 18:21:19,178] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 18:21:19,178] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 18:21:19,179] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 18:21:19,341] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,341] {models.py:1342} INFO - Executing <Task(PythonOperator): query.q6> on 2018-05-29 18:21:16.048103
[2018-05-29 18:21:19,405] {base_task_runner.py:95} INFO - Subtask: (13, 'q7', 'MATCH(n) RETURN COUNT(n)', 'neo4j')
[2018-05-29 18:21:19,406] {base_task_runner.py:95} INFO - Subtask: ['id_', 'counts']
[2018-05-29 18:21:19,406] {base_task_runner.py:95} INFO - Subtask: ========================================
[2018-05-29 18:21:19,406] {base_task_runner.py:95} INFO - Subtask: Executing query  q7
[2018-05-29 18:21:19,406] {base_task_runner.py:95} INFO - Subtask: {}
[2018-05-29 18:21:19,406] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,405] {connection.py:449} INFO - ~~ [CONNECT] ('127.0.0.1', 7687)
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,406] {models.py:1417} ERROR - Cannot acquire connection to Address(host='localhost', port=7687)
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 18:21:19,419] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 50, in execute_query
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:     driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth("neo4j", "password"))
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/api.py", line 109, in driver
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:     return driver_class(uri, **config)
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/direct.py", line 65, in __init__
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:     pool.acquire()
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/direct.py", line 44, in acquire
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask:     raise ServiceUnavailable("Cannot acquire connection to {!r}".format(self.address))
[2018-05-29 18:21:19,420] {base_task_runner.py:95} INFO - Subtask: neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host='localhost', port=7687)
[2018-05-29 18:21:19,421] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,419] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 18:21:19,574] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:21:19,574] {models.py:1462} ERROR - Cannot acquire connection to Address(host='localhost', port=7687)
[2018-05-29 18:21:19,574] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 18:21:19,575] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 18:21:19,575] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing DbApiHook directly from <module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'> has been deprecated. Please import from '<module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 18:21:19,575] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 18:21:19,575] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 18:21:19,575] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 18:21:19,577] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 18:21:19,577] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 18:21:19,577] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 18:21:19,577] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 18:21:19,577] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 50, in execute_query
[2018-05-29 18:21:19,578] {base_task_runner.py:95} INFO - Subtask:     driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth("neo4j", "password"))
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/api.py", line 109, in driver
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:     return driver_class(uri, **config)
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/direct.py", line 65, in __init__
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:     pool.acquire()
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/neo4j/v1/direct.py", line 44, in acquire
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask:     raise ServiceUnavailable("Cannot acquire connection to {!r}".format(self.address))
[2018-05-29 18:21:19,579] {base_task_runner.py:95} INFO - Subtask: neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host='localhost', port=7687)
[2018-05-29 18:21:23,381] {jobs.py:2083} INFO - Task exited with return code 1
