[2018-05-29 17:39:08,048] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 17:39:08,565] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run example query.q6 2018-05-29T17:39:06.031811 --job_id 3 --raw -sd DAGS_FOLDER/example.py']
[2018-05-29 17:39:08,770] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:08,770] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 17:39:09,000] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,000] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 17:39:09,376] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,376] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 17:39:06.031811 [queued]>
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,377] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 17:39:06.031811 [queued]>
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,377] {models.py:1318} INFO - 
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 17:39:09,377] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 17:39:09,484] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,484] {models.py:1342} INFO - Executing <Task(PythonOperator): query.q6> on 2018-05-29 17:39:06.031811
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,501] {models.py:1417} ERROR - no such table: myapp_query
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 17:39:09,502] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 27, in execute_query
[2018-05-29 17:39:09,503] {base_task_runner.py:95} INFO - Subtask:     c.execute('SELECT * FROM myapp_query WHERE name=?',(query_name,))
[2018-05-29 17:39:09,503] {base_task_runner.py:95} INFO - Subtask: sqlite3.OperationalError: no such table: myapp_query
[2018-05-29 17:39:09,503] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,502] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 17:39:09,616] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:39:09,616] {models.py:1462} ERROR - no such table: myapp_query
[2018-05-29 17:39:09,616] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 17:39:09,616] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 17:39:09,616] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 17:39:09,616] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 27, in execute_query
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask:     c.execute('SELECT * FROM myapp_query WHERE name=?',(query_name,))
[2018-05-29 17:39:09,617] {base_task_runner.py:95} INFO - Subtask: sqlite3.OperationalError: no such table: myapp_query
[2018-05-29 17:39:13,659] {jobs.py:2083} INFO - Task exited with return code 1
